apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: golang-microservice-starter
  title: Golang Microservice 1.0
  description: get started with microservice in golang created using cookiecutter
spec:
  owner: nmnjn
  type: service

  parameters:
    - title: Enter project information
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the service
          'ui:autofocus': true
          'ui:options':
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          'ui:field': OwnerPicker
          'ui:options':
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          'ui:field': RepoUrlPicker
          'ui:options':
            allowedHosts:
              - bitbucket.org
  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: 'fetch:cookiecutter'
      input:
        url: ./
        copyWithoutRender: ["template.yaml"]
        values:
          project_name: '${{ parameters.name }}'
          project_owner: '${{ parameters.owner }}'
          url: config.getString('app.baseUrl')